before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qbs qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev

script:
  - pushd deps/h264bitstream
  - autoreconf -i
  - ./configure
  - make
  - popd
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt /usr/bin/qmake qt5
  - qbs config defaultProfile qt5
  - qbs build
