before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qbs qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev

script:
  - git submodule init
  - git submodule update
  - pushd deps/h264bitstream
  - ./configure
  - make
  - popd
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs build
